import { forwardRef } from 'react';
import { Bus, Clock, MapPin, Phone } from 'lucide-react';

export interface BusRoute {
    id: string;
    busNumber: string;
    route: string;
    time: string;
    price?: string;
    driver?: string;
    contact?: string;
}

export interface ScheduleData {
    companyName: string;
    date: string;
    buses: BusRoute[];
}

interface SchedulePreviewProps {
    data: ScheduleData;
}



export const SchedulePreview = forwardRef<HTMLDivElement, SchedulePreviewProps>(({ data }, ref) => {
    return (
        <div ref={ref} className="bg-slate-900 p-8 rounded-none w-[1080px] min-h-[1080px] text-white relative overflow-hidden flex flex-col">
            {/* Background Design */}
            <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-primary via-secondary to-primary" />
            <div className="absolute bottom-0 left-0 w-full h-2 bg-gradient-to-r from-primary via-secondary to-primary" />

            <div className="absolute top-[-20%] right-[-20%] w-[60%] h-[60%] bg-primary/10 rounded-full blur-[150px]" />
            <div className="absolute bottom-[-20%] left-[-20%] w-[60%] h-[60%] bg-secondary/10 rounded-full blur-[150px]" />

            {/* Header */}
            <div className="text-center space-y-4 mb-12 relative z-10">
                <h1 className="text-6xl font-display font-bold uppercase tracking-wider text-transparent bg-clip-text bg-gradient-to-r from-white to-gray-400 filter drop-shadow-lg">
                    {data.companyName || "Company Name"}
                </h1>
                <div className="inline-block px-8 py-3 rounded-full bg-white/10 border border-white/20 backdrop-blur-md">
                    <p className="text-2xl font-medium text-primary tracking-widest uppercase">
                        {data.date ? new Date(data.date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) : "Select Date"}
                    </p>
                </div>
            </div>

            {/* Table Header */}
            <div className="grid grid-cols-12 gap-4 px-6 py-4 bg-white/10 rounded-t-2xl border-b border-white/20 font-bold text-xl uppercase tracking-wider text-primary">
                <div className="col-span-2 flex items-center gap-2"><Bus className="w-6 h-6" /> Bus No</div>
                <div className="col-span-4 flex items-center gap-2"><MapPin className="w-6 h-6" /> Route</div>
                <div className="col-span-3 flex items-center gap-2"><Clock className="w-6 h-6" /> Departure</div>
                <div className="col-span-3 flex items-center gap-2 text-right justify-end">Price / Contact</div>
            </div>

            {/* Table Body */}
            <div className="flex-1 space-y-2 relative z-10">
                {data.buses.length === 0 ? (
                    <div className="text-center py-20 text-gray-500 text-2xl italic">
                        Add buses to see them here...
                    </div>
                ) : (
                    data.buses.map((bus, index) => (
                        <div
                            key={bus.id}
                            className={`grid grid-cols-12 gap-4 px-6 py-5 items-center border-b border-white/5 ${index % 2 === 0 ? 'bg-white/5' : 'bg-transparent'}`}
                        >
                            <div className="col-span-2 font-bold text-2xl text-secondary">{bus.busNumber}</div>
                            <div className="col-span-4 text-xl font-medium text-gray-200">{bus.route}</div>
                            <div className="col-span-3 text-2xl font-bold text-white bg-primary/20 px-3 py-1 rounded-lg w-fit border border-primary/30 whitespace-nowrap">
                                {formatTime(bus.time)}
                            </div>
                            <div className="col-span-3 text-right space-y-1">
                                {bus.price && <div className="text-xl font-bold text-green-400">{bus.price}</div>}
                                {bus.contact && (
                                    <div className="flex items-center justify-end gap-2 text-sm text-gray-400">
                                        <Phone className="w-4 h-4" /> {bus.contact}
                                    </div>
                                )}
                            </div>
                        </div>
                    ))
                )}
            </div>

            {/* Footer */}
            <div className="mt-auto pt-8 border-t border-white/10 flex justify-between items-end relative z-10">
                <div className="text-left">
                    <p className="text-sm text-gray-500 uppercase tracking-widest">Generated by</p>
                    <p className="text-lg font-bold text-primary">Bus Schedule Generator PRO</p>
                </div>
                <div className="text-right">
                    <p className="text-sm text-gray-500 mb-1">Total Buses: {data.buses.length}</p>
                    <p className="text-xs text-gray-600 font-medium tracking-wide">Build with love by Raees Awan</p>
                </div>
            </div>
        </div>
    );
});

// Helper for AM/PM
const formatTime = (timeStr: string) => {
    if (!timeStr) return "--:--";
    const [hours, minutes] = timeStr.split(':');
    const h = parseInt(hours, 10);
    if (isNaN(h)) return timeStr;
    const ampm = h >= 12 ? 'PM' : 'AM';
    const h12 = h % 12 || 12;
    return `${h12}:${minutes} ${ampm}`;
};

SchedulePreview.displayName = "SchedulePreview";
